@baseUrl = http://localhost:8000
@model_name = gpt-4o-mini
@model_name = llama3.1:latest
# @model_name = claude-3-5-sonnet-20240620
# @model_name = llama-3.1-70b-versatile
# @model_name = mistralai/Mixtral


### Generar embedding
POST {{baseUrl}}/sessions/sync_from_firebase/knowcker
Content-Type: application/json

{
    
}

### Generar embedding
POST {{baseUrl}}/sessions/sync_to_firebase/knowcker
Content-Type: application/json

{
    
}